version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: corporate-db
    networks:
      - banknet
    environment:
      - POSTGRES_DB=micro-banking-db
      - POSTGRES_USER=${CORPORATE_DB_USERNAME}
      - POSTGRES_PASSWORD=${CORPORATE_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  nickname-service:
    build: ../nickname-service
    depends_on:
      - db
    networks:
      - banknet
    ports:
      - "3001:3001"
      - "9098:9098"
    environment:
      - DB_URL=${CORPORATE_DB_URL}
      - DB_USERNAME=${CORPORATE_DB_USERNAME}
      - DB_PASSWORD=${CORPORATE_DB_PASSWORD}

networks:
  banknet:
    external: true

volumes:
  postgres_data:

