name: Microservice CI/CD

on:
  push:
    branches:
      - 'ft/*'
      - dev
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect-changes:
    uses: ./.github/workflows/detect-changes.yml

  build-test:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.changed-services != '[]' }}
    uses: ./.github/workflows/build-and-test.yml
    with:
      changed-services: ${{ needs.detect-changes.outputs.changed-services }}
    secrets: inherit
